services:
  mysql:
    image: mysql:8.1
    container_name: green-energy-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3308:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  app:
    build: .
    container_name: green-energy-app
    restart: always
    ports:
      - "8880:8080"
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DB_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DB_PASSWORD}
    depends_on:
      - mysql

volumes:
  mysql-data:
